### ISSUE TITLE
Investigate SHA256 Hashing on iOS (Swift)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/time-apple-watch-app#84]
It _appears_ to be _possible_ to create a `SHA256` Hash in Swift:
https://stackoverflow.com/questions/25388747/sha256-in-swift

## Todo

+ [x] Convert Task/Timer to JSON - https://developer.apple.com/swift/blog/?id=37
+ [x] Convert JSON to String
+ [x] SHA256 Hash the String
+ [ ] write a test to check for the output for the SHA256 Hash functions 👍
+ [ ] Use the Hash as the ID in SQL-Lite DB locally on device
+ [ ] Put hash into JSON Object as `id` field
+ [ ] Send Strigified JSON to API (_including `id:hash`_)

## Background Reading

+ [x] Merkle Tree: https://en.wikipedia.org/wiki/Merkle_tree

Note: the _reason_ for using a `SHA256` instead of another hashing algorithm is: https://github.com/dwyl/learn-cryptography/issues/2

**Comment by nelsonic** [comment]
@sohilpandya please remember to add a Time Estimate to issues before diving in. 😉

**Comment by sohilpandya** [comment]
Thanks for that @nelsonic.

I've estimated 1.5 days for this, already spent ~3 hours on the first couple if items alongside the background reading. :)

**update**
- I am trying to implement this whole method on just the starting of a timer. 
- Once the flow has been implemented for this, I can replicate it for when a timer ends.

**Comment by sohilpandya** [comment]
@nelsonic wanted a clarification on the following point:
> Use the Hash as the ID in SQL-Lite DB locally on device

At this moment we are storing the following information in core data:
<img width="146" alt="screen shot 2017-06-23 at 10 35 48 1" src="https://user-images.githubusercontent.com/2305591/27476215-bf438122-57ff-11e7-9bce-eb1cba8b41b6.png">

I will be adding an additional field in the core data called `id` which will contain the hash. 
- Every time a timer is started we create this item in the core data. It will contain the hash.

Now when the user stops a timer, we are updating this item in the core data, would we update the hash too? as at the moment, the user starts a timer the hash contains the following infomation
```
{
  "project_name": "iOS",
  "start_date": "Stringified Date",
  "isTaskRunning": "true"
}
```
But when the timer is stopped it should have an additional field of `"end_date":"Stringified Date"`

This will mean that the hash will be different when the timer is started and when the timer is stopped.

**Comment by nelsonic** [comment]
@sohilpandya apologies if this is unclear. no, we are not updating the hash we are going to save a new revision. I am working on NHS today, but as soon as I have some time spare I will document _exactly_ how this needs to work on both iOS and PWA so it's _much_ clearerer. 👍 

Meanwhile could you please write-up a "complete beginners" intro to automated UI testing in: https://github.com/dwyl/learn-apple-watch-development/ thanks! 🎉

**Comment by sohilpandya** [comment]
Thanks for that! I'll probably like to catch up about it early Monday morning if we can, I will look into https://github.com/dwyl/learn-apple-watch-development/issues/40 for the time being. 👍

**Comment by sohilpandya** [comment]
@nelsonic can we catch up at some point today to talk about this?

**Comment by nelsonic** [comment]
@sohilpandya dang. only saw this now... I expect to do some work on this on the train on Thursday. we should setup a hangout to catchup. 👍

**Comment by sohilpandya** [comment]
Hey @nelsonic That would be awesome, I'm planning to start working full steam from tomorrow so be great if we could catch up first thing tomorrow if that is possible?

**Comment by sohilpandya** [comment]
We only have one table, some of the main bits of information it contains:

| **core data** |
| --------- |
| project_name |
| task_start_date |
| task_end_date |
| is_running |

Here is the current flow of all the times we are storing to the **core data**
- saving new project (create)
- start a new timer (create)
- stopping a new timer (update)
