### ISSUE TITLE
Next set of tasks

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/time-apple-watch-app#95]
Hi, @iteles & @nelsonic, I'm just writing down some of the next actions steps that I can take over the next few weeks, We can also discuss this during the stand-up today. I am finding it difficult to keep the momentum going as I don't have a clear sight of the next potential steps for me. So I'll write down some of the things that can be done as next steps. I'd like for you to approve each individual item and make additions to it if you like. But I am hoping that having a list will keep the flow going for me. 

- [ ] Gradual Colour Change for Projects #90 
- [x] Bug where the apple watch interface is getting refreshed twice if a timer is running #94
- [x] Apple watch adds title of the app to the top left corner and remove from the main screen. 
- [ ] Apple Watch - what should happen in the case of no connection to the phone. #73 
- [ ] Testflight setup Tutorial on Learn repo #43 
- [ ] Create new tutorial for how parsing JSON works in Swift 4
- [ ] Refactor some of the functionality happening on the Phone. Currently, a lot of things happen within the view controllers and I'd like to try to separate the concerns. 
- [ ] Restructure the layout of the project details page. I would like to spend 15 mins with @iteles @nelsonic on discussing how this page should look, I have some ideas but want to start a conversation. 

We also have this issue 
- [ ] Investigate SHA256 hashing on iOS #84 but waiting for an update on that. 

The above order is the way I'd like to start tackling items If you have any questions or if you don't want me to work on any of the above issues then please let me know as a comment on this issue so that we can discuss alternate steps. Otherwise, I'll start tackling these one at a time.
